/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mosqueira.trackfit;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import mosqueira.trackfit.dataAccess.DataAccess;
import mosqueira.trackfit.dto.Exercicis;
import mosqueira.trackfit.dto.Usuaris;
import mosqueira.trackfit.dto.Workouts;

/**
 *
 * @author Lulas
 */
public class ListPanelUsuariosAsignados extends javax.swing.JPanel {

    private Main jFrameMain;
    private Usuaris instructor;
    private DataAccess da = new DataAccess();
    private List<Usuaris> usuari=new ArrayList<>();
    private JLabel lblUser;
    private List<Workouts> userWorkouts=new ArrayList<>();
    /**
     * Creates new form ListPanel
     */
    public ListPanelUsuariosAsignados(Main jFrameMain) {
        initComponents();
        this.instructor =instructor;
        this.jFrameMain = jFrameMain;
        add(userSecction);
        loadAssignedUsers();
        lblUser = new JLabel();
        inicializarTabla();
         //cargarExerciciCombo();
        //cargarUsuariosComboBox();
       
    }
    /*private void cargarExerciciCombo() {
        List<Exercicis> exercicisList = da.getInfoExercicis();
        jComboBoxExercici.removeAllItems();
        jComboBoxExercici.addItem("Select an exercise");
        for (Exercicis ex : exercicisList) {
            jComboBoxExercici.addItem(ex.getNomExercici());
        }
    
    }*/
    /*private LocalDateTime obtenerFechaDelSpinner() {
        java.util.Date fechaSeleccionada = (java.util.Date) jSpinner1.getValue();
        if (fechaSeleccionada != null) {
            return LocalDateTime.ofInstant(fechaSeleccionada.toInstant(), ZoneId.systemDefault());
        }
        return LocalDateTime.now();
    }*/
   
    private void loadAssignedUsers() {
        List <Usuaris>usuari=da.getInstrutor();
        DefaultComboBoxModel dcbm=new DefaultComboBoxModel<>();
        for(Usuaris u:usuari){
            dcbm.addElement(u);
        }
        jComboBoxUsers.setModel(dcbm); 
        updateTable(new ArrayList<Workouts>());
    }
    public void setUsuario(Usuaris usuario) {
        this.instructor = usuario; // Almacena la referencia del instructor
        // Si el usuario no es nulo, muestra su nombre
        if (usuario != null) {
            
        } else {
            userSecction.setText("Usuario no autenticado");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormulario = new javax.swing.JDialog();
        jLabelDate = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxUsersWork = new javax.swing.JComboBox<>();
        jListUsers = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jTextComment = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButtonGuardar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBoxUsers = new javax.swing.JComboBox<>();
        jListaUser = new javax.swing.JLabel();
        jLogo = new javax.swing.JLabel();
        userSecction = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jUserTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListExercici = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonCrearWorkouts = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonVer = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();

        jFormulario.setMinimumSize(new java.awt.Dimension(400, 400));
        jFormulario.getContentPane().setLayout(null);

        jLabelDate.setBackground(new java.awt.Color(255, 255, 153));
        jLabelDate.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jLabelDate.setText("For Date");
        jFormulario.getContentPane().add(jLabelDate);
        jLabelDate.setBounds(50, 30, 90, 30);

        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormulario.getContentPane().add(jSeparator3);
        jSeparator3.setBounds(40, 160, 360, 40);

        jComboBoxUsersWork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jFormulario.getContentPane().add(jComboBoxUsersWork);
        jComboBoxUsersWork.setBounds(180, 100, 180, 30);

        jListUsers.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        jListUsers.setText(" Users List");
        jFormulario.getContentPane().add(jListUsers);
        jListUsers.setBounds(50, 100, 110, 30);

        jSeparator5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormulario.getContentPane().add(jSeparator5);
        jSeparator5.setBounds(40, 30, 360, 40);
        jFormulario.getContentPane().add(jTextComment);
        jTextComment.setBounds(180, 160, 180, 30);

        jSeparator6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jFormulario.getContentPane().add(jSeparator6);
        jSeparator6.setBounds(40, 100, 360, 40);

        jLabel4.setText("Comment");
        jFormulario.getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 170, 80, 20);

        jSpinner1.setModel(new javax.swing.SpinnerDateModel());
        jFormulario.getContentPane().add(jSpinner1);
        jSpinner1.setBounds(180, 30, 180, 30);

        jButtonGuardar.setText("Add");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jFormulario.getContentPane().add(jButtonGuardar);
        jButtonGuardar.setBounds(80, 210, 100, 23);

        jButton1.setText("Cancel");
        jFormulario.getContentPane().add(jButton1);
        jButton1.setBounds(230, 210, 90, 23);

        setBackground(new java.awt.Color(255, 255, 204));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMinimumSize(new java.awt.Dimension(652, 395));
        setPreferredSize(new java.awt.Dimension(560, 620));
        setRequestFocusEnabled(false);
        setLayout(null);

        jComboBoxUsers.setBackground(new java.awt.Color(255, 204, 153));
        jComboBoxUsers.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxUsers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUsers.setPreferredSize(new java.awt.Dimension(652, 395));
        jComboBoxUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUsersActionPerformed(evt);
            }
        });
        add(jComboBoxUsers);
        jComboBoxUsers.setBounds(370, 90, 160, 30);

        jListaUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jListaUser.setForeground(new java.awt.Color(255, 102, 0));
        jListaUser.setText("List Users");
        add(jListaUser);
        jListaUser.setBounds(410, 60, 100, 20);

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLogo.setText("jLabel2");
        jLogo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        jLogo.setPreferredSize(new java.awt.Dimension(150, 150));
        jLogo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add(jLogo);
        jLogo.setBounds(350, 10, 180, 40);

        userSecction.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        userSecction.setForeground(new java.awt.Color(255, 102, 0));
        userSecction.setText("NomUsuari");
        add(userSecction);
        userSecction.setBounds(250, 10, 130, 30);

        jUserTable.setBackground(new java.awt.Color(153, 153, 153));
        jUserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jUserTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jUserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jUserTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 240, 70);

        jListExercici.setBackground(new java.awt.Color(255, 153, 102));
        jListExercici.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jListExercici.setForeground(new java.awt.Color(0, 0, 0));
        jListExercici.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lista de Ejercicios" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListExercici);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 290, 150, 120);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Exercicis List");
        add(jLabel1);
        jLabel1.setBounds(20, 250, 140, 30);

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Workouts Table");
        add(jLabel2);
        jLabel2.setBounds(30, 20, 150, 30);

        jButtonCrearWorkouts.setBackground(new java.awt.Color(255, 153, 102));
        jButtonCrearWorkouts.setText("Crear");
        jButtonCrearWorkouts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCrearWorkouts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearWorkoutsActionPerformed(evt);
            }
        });
        add(jButtonCrearWorkouts);
        jButtonCrearWorkouts.setBounds(20, 170, 70, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 51));
        jLabel3.setText("New Workouts");
        add(jLabel3);
        jLabel3.setBounds(20, 150, 100, 20);

        jButtonVer.setBackground(new java.awt.Color(255, 153, 102));
        jButtonVer.setText("Ver");
        add(jButtonVer);
        jButtonVer.setBounds(170, 290, 80, 23);

        jButtonAgregar.setBackground(new java.awt.Color(255, 153, 102));
        jButtonAgregar.setText("Agregar");
        add(jButtonAgregar);
        jButtonAgregar.setBounds(170, 350, 80, 23);

        jButtonModificar.setBackground(new java.awt.Color(255, 153, 102));
        jButtonModificar.setText("Modificar");
        add(jButtonModificar);
        jButtonModificar.setBounds(170, 320, 81, 23);

        jButtonEliminar.setBackground(new java.awt.Color(255, 153, 102));
        jButtonEliminar.setText("Delete");
        add(jButtonEliminar);
        jButtonEliminar.setBounds(170, 380, 80, 23);
    }// </editor-fold>//GEN-END:initComponents
    
  
    
    
    private void jComboBoxUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUsersActionPerformed
        // TODO add your handling code here:
        // Verifica si se seleccionó un item
        //usuari=da.getAssignedInstrutor();  
        Usuaris selectedUser=(Usuaris)jComboBoxUsers.getSelectedItem();
        if (selectedUser!= null) {  
            int userId= selectedUser.getId();
            lblUser.setText(selectedUser.toString());
            userWorkouts=da.getWorkoutsUser(userId);
            updateTable(userWorkouts);
        }
    }//GEN-LAST:event_jComboBoxUsersActionPerformed
    private void inicializarTabla(){
        DefaultTableModel dtm=new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"UserId","IdWorkouts","ForDate","Comments"} );
        jUserTable.setModel(dtm);
       
    }
    private void updateTable(List<Workouts> workouts){
        DefaultTableModel dtm=(DefaultTableModel)jUserTable.getModel();
        dtm.setRowCount(0);
        userWorkouts=workouts;
        for(Workouts workout: workouts){
            dtm.addRow(new Object[]{workout.getUserId(),workout.getId(),workout.getForDate(),workout.getComments()});
        }
    }

    private void updateListExercicis(List<Exercicis> exercici){
    DefaultListModel<String> listModel = new DefaultListModel<>();
    for (Exercicis ex : exercici) {
        listModel.addElement(ex.getNomExercici()+" " + ex.getDescripcio());
        
    }
    jListExercici.setModel(listModel);
}

    
    private void jUserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserTableMouseClicked
        int selectedRow = jUserTable.getSelectedRow();
        if (selectedRow != -1) {
            // Obtenemos el workout seleccionado
            int workoutId=(int)jUserTable.getValueAt(selectedRow, 1);
           // Workouts selectedWorkout = userWorkouts.get(selectedRow);

            // Obtenemos los ejercicios correspondientes a ese workout
            List<Exercicis> exercicis = da.getExercicisForWorkout(workoutId);

            // Actualizamos la lista de ejercicios
            updateListExercicis(exercicis);
        }
    }//GEN-LAST:event_jUserTableMouseClicked

    
    private void jButtonCrearWorkoutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearWorkoutsActionPerformed
     /*Exercicis ejercicioSeleccionado = obtenerEjercicioSeleccionado();
        if (ejercicioSeleccionado != null) {
            // Aquí podrías llenar los campos de `jFormulario` con los datos del ejercicio seleccionado
            jTextUserId.setText("");
            jTextComment.setText("");

            // Muestra el diálogo
            jFormulario.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario para asignarle el ejercicio.");
        }  */             
    }//GEN-LAST:event_jButtonCrearWorkoutsActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       // Obtener los valores de los campos
        String comments = jTextComment.getText();
        Usuaris usuariSeleccionado=(Usuaris)jComboBoxUsersWork.getSelectedItem();
        // Obtener el usuario seleccionado
        int userId = usuariSeleccionado.getId();
        Date dateWork=(Date)jSpinner1.getValue();
        SimpleDateFormat dateFormat=new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String fecha=dateFormat.format(dateWork);

        // Crear un nuevo objeto Workouts
        Workouts nuevoWorkout = new Workouts();
        nuevoWorkout.setForDate(fecha);
        nuevoWorkout.setUserId(userId);
        nuevoWorkout.setComments(comments);

        // Aquí puedes guardar el nuevo workout en la base de datos o en memoria
        da.saveWorkout(nuevoWorkout);  // Asegúrate de implementar el método saveWorkout en DataAccess.

        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Workout creado correctamente.");
                  
    }//GEN-LAST:event_jButtonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCrearWorkouts;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JComboBox<String> jComboBoxUsers;
    private javax.swing.JComboBox<String> jComboBoxUsersWork;
    private javax.swing.JDialog jFormulario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JList<String> jListExercici;
    private javax.swing.JLabel jListUsers;
    private javax.swing.JLabel jListaUser;
    private javax.swing.JLabel jLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextComment;
    private javax.swing.JTable jUserTable;
    private javax.swing.JLabel userSecction;
    // End of variables declaration//GEN-END:variables
}