/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mosqueira.trackfit;
import mosqueira.trackfit.views.ListPanelUsuariosAsignados;
import javax.swing.JOptionPane;
import mosqueira.trackfit.dto.Usuaris;
import mosqueira.trackfit.views.DialogLogin;


/**
 *
 * @author Lulas
 */
public class Main extends javax.swing.JFrame {
    private ListPanelUsuariosAsignados listF;
    private Usuaris instructor;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setSize(700, 500);
        jPanelMain.setBounds(0, 0, 700, 500);
        getContentPane().add(jPanelMain);
        setLocationRelativeTo(this);
        repaint(); 
    }  
    
    public void showListFrame(Usuaris u){
        this.instructor=u;
        getContentPane().removeAll();
        // Crear el panel ListUsers y pasarlo al marco
        listF = new ListPanelUsuariosAsignados(this, instructor);
        listF.setBounds(0, 0, 700, 600); // Definir las posiciones y tamaños manualmente
        // Agregar el panel de usuarios
        getContentPane().add(listF);
        listF.revalidate();
        repaint();
        }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jlogo = new javax.swing.JLabel();
        JsitioWeb = new javax.swing.JLabel();
        IraDialogo = new javax.swing.JButton();
        jMenuFrame = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.GreyInline"));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelMain.setBackground(new java.awt.Color(249, 249, 231));
        jPanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMain.setForeground(new java.awt.Color(249, 249, 231));
        jPanelMain.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanelMain.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanelMain.setRequestFocusEnabled(false);
        jPanelMain.setLayout(null);

        jlogo.setBackground(new java.awt.Color(191, 154, 207));
        jlogo.setForeground(new java.awt.Color(204, 204, 255));
        jlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jPanelMain.add(jlogo);
        jlogo.setBounds(210, 60, 180, 160);

        JsitioWeb.setForeground(new java.awt.Color(0, 0, 0));
        JsitioWeb.setText("<html><u>Visita nuestro sitio web</u></html>");
        JsitioWeb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JsitioWebMouseClicked(evt);
            }
        });
        jPanelMain.add(JsitioWeb);
        JsitioWeb.setBounds(240, 230, 130, 40);

        IraDialogo.setBackground(new java.awt.Color(255, 204, 153));
        IraDialogo.setForeground(new java.awt.Color(0, 0, 0));
        IraDialogo.setText("Access");
        IraDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IraDialogoActionPerformed(evt);
            }
        });
        jPanelMain.add(IraDialogo);
        IraDialogo.setBounds(270, 300, 72, 23);

        getContentPane().add(jPanelMain);
        jPanelMain.setBounds(0, -20, 630, 530);

        jMenuFrame.setBackground(new java.awt.Color(255, 255, 255));
        jMenuFrame.setBorder(null);
        jMenuFrame.setForeground(new java.awt.Color(255, 153, 51));

        jMenuFile.setBackground(new java.awt.Color(255, 153, 102));
        jMenuFile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuFile.setText("File");
        jMenuFile.setMinimumSize(new java.awt.Dimension(652, 395));
        jMenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFileActionPerformed(evt);
            }
        });

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuExit);

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenuFile.add(logout);

        jMenuFrame.add(jMenuFile);

        jMenuHelp.setBackground(new java.awt.Color(255, 153, 102));
        jMenuHelp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuHelp.setText("Help");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItem1);

        jMenuFrame.add(jMenuHelp);

        setJMenuBar(jMenuFrame);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void JsitioWebMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JsitioWebMouseClicked
        // TODO add your handling code here:
       try {
        // Abre la URL en el navegador
            String url = "http://www.ejemplo.com/"; // Reemplaza con la URL de tu aplicación
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (Exception e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_JsitioWebMouseClicked

    private void IraDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IraDialogoActionPerformed
       // Crear el cuadro de diálogo para el inicio de sesión
        DialogLogin iraDialogo = new DialogLogin(this, true);
        iraDialogo.setVisible(true); 
    }//GEN-LAST:event_IraDialogoActionPerformed

    private void jMenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFileActionPerformed
        System.exit(0); 
    }//GEN-LAST:event_jMenuFileActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          JOptionPane.showMessageDialog(this,
                "Developed by Romina Marlene Mosqueira Rodriguez\n"
                + "Course: 2º DAM \n"
                + "Resources used:\n"
                + "- Logo: Canva\n"
                + "- Other resources: Teacher, Classmates, ChatGPT"); 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        getContentPane().add(jPanelMain);
        jPanelMain.setVisible(true);
        listF.setVisible(false);
        JOptionPane.showMessageDialog(this, "Logout successful", "Logout", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IraDialogo;
    private javax.swing.JLabel JsitioWeb;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuBar jMenuFrame;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JLabel jlogo;
    private javax.swing.JMenuItem logout;
    // End of variables declaration//GEN-END:variables
}