/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mosqueira.trackfit;

import at.favre.lib.crypto.bcrypt.BCrypt;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import mosqueira.trackfit.dataAccess.DataAccess;
import mosqueira.trackfit.dto.Usuari;

/**
 *
 * @author Lulas
 */
public class NewJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(JFrame jFrame, boolean modal) {
        super(jFrame, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        Email = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        checkInstructor = new javax.swing.JCheckBox();
        ButtonRegister = new javax.swing.JButton();
        lblInfoMessage = new javax.swing.JLabel();
        botonAcceso = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.black);
        setModal(true);
        setPreferredSize(new java.awt.Dimension(437, 395));
        getContentPane().setLayout(null);

        Email.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        Email.setText("Introduce Email:");
        getContentPane().add(Email);
        Email.setBounds(110, 80, 106, 16);

        txtEmail.setText("a@b.c");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(110, 110, 85, 22);

        Password.setFont(new java.awt.Font("SansSerif", 3, 12)); // NOI18N
        Password.setText("Introduce Password:");
        getContentPane().add(Password);
        Password.setBounds(100, 140, 119, 16);

        txtPassword.setText("1234");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword);
        txtPassword.setBounds(110, 170, 84, 22);

        checkInstructor.setText("Check");
        checkInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInstructorActionPerformed(evt);
            }
        });
        getContentPane().add(checkInstructor);
        checkInstructor.setBounds(80, 240, 70, 20);

        ButtonRegister.setText("Register");
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRegister);
        ButtonRegister.setBounds(160, 240, 90, 23);
        getContentPane().add(lblInfoMessage);
        lblInfoMessage.setBounds(10, 350, 0, 0);

        botonAcceso.setText("Login");
        botonAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAccesoActionPerformed(evt);
            }
        });
        getContentPane().add(botonAcceso);
        botonAcceso.setBounds(80, 280, 72, 23);

        jButtonRegresar.setText("Return");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegresar);
        jButtonRegresar.setBounds(180, 280, 72, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        Usuari nuevoUsuario = new Usuari();
        //nuevoUsuario.setNom(txtNombre.getText());
        nuevoUsuario.setEmail(txtEmail.getText());
        String passwordHash = BCrypt.withDefaults().hashToString(12, txtPassword.getPassword());
        nuevoUsuario.setPasswordHash(passwordHash);
        nuevoUsuario.setInstructor(checkInstructor.isSelected());

        DataAccess da = new DataAccess();
        int nuevoUsuarioId = da.registerUser(nuevoUsuario);
        nuevoUsuarioId = da.getLastInsertedUserId();
        nuevoUsuario.setId(nuevoUsuarioId);
        lblInfoMessage.setText("User registered successFully with Id " + nuevoUsuarioId);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void checkInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInstructorActionPerformed

    private void botonAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccesoActionPerformed
        // TODO add your handling code here:

        Usuari usuari = DataAccess.getUsuario(txtEmail.getText());
        if (usuari.Instructor()) {
            //Comprobar password
            char[] passwordToVerify = txtPassword.getPassword();
            String userPasswordHashDataBase = usuari.getPasswordHash();
            var result = BCrypt.verifyer().verify(passwordToVerify, userPasswordHashDataBase);
            if (result.verified) {
                JOptionPane.showMessageDialog(this, "Login succesful .Welcome " + usuari.getNom() + ".");
            } else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error User not found");
    }//GEN-LAST:event_botonAccesoActionPerformed
    }
    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Password;
    private javax.swing.JButton botonAcceso;
    private javax.swing.JCheckBox checkInstructor;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel lblInfoMessage;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

}
