/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mosqueira.trackfit.views;

import at.favre.lib.crypto.bcrypt.BCrypt;
import javax.swing.JOptionPane;
import mosqueira.trackfit.Main;
import mosqueira.trackfit.dataAccess.DataAccess;
import mosqueira.trackfit.dto.Usuaris;

/**
 *
 * @author Lulas
 */
public class DialogLogin extends javax.swing.JDialog {
    private Main mainFra;
    private DataAccess da=new DataAccess();
    private Usuaris loggedInUser;
    
    /**
     * Creates new form NewJDialog
     */
    public DialogLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initComponents();
        this.mainFra = (Main)parent;   
        setLocationRelativeTo(this);// CENTRAR LA VENTANA 
    }
     public Usuaris getLoggedInUser() {
            return loggedInUser; 
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonAcceso = new javax.swing.JButton();
        ButtonRegister = new javax.swing.JButton();
        Password = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        checkInstructor = new javax.swing.JCheckBox();
        lblInfoMessage = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenufile = new javax.swing.JMenu();
        jMenuReturn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.black);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(500, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(249, 249, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(null);

        botonAcceso.setText("Login");
        botonAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAccesoActionPerformed(evt);
            }
        });
        jPanel1.add(botonAcceso);
        botonAcceso.setBounds(300, 440, 72, 23);

        ButtonRegister.setText("Register");
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonRegister);
        ButtonRegister.setBounds(370, 380, 90, 23);

        Password.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 153, 102));
        Password.setText("Introduce Password:");
        jPanel1.add(Password);
        Password.setBounds(260, 290, 150, 30);

        txtPassword.setText("string");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(290, 330, 90, 22);

        checkInstructor.setText("Check");
        checkInstructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInstructorActionPerformed(evt);
            }
        });
        jPanel1.add(checkInstructor);
        checkInstructor.setBounds(260, 380, 70, 20);
        jPanel1.add(lblInfoMessage);
        lblInfoMessage.setBounds(10, 350, 0, 0);

        Email.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 153, 102));
        Email.setText("Introduce Email:");
        jPanel1.add(Email);
        Email.setBounds(280, 210, 140, 30);

        txtEmail.setText("a@b.c");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(290, 260, 90, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 50, 180, 160);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 690, 580);

        jMenufile.setText("File");
        jMenufile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenufileActionPerformed(evt);
            }
        });

        jMenuReturn.setText("Return...");
        jMenuReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReturnActionPerformed(evt);
            }
        });
        jMenufile.add(jMenuReturn);

        jMenuBar1.add(jMenufile);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        Usuaris nuevoUsuario = new Usuaris();
        //nuevoUsuario.setNom(txtNombre.getText());
        nuevoUsuario.setEmail(txtEmail.getText());
        String passwordHash = BCrypt.withDefaults().hashToString(12, txtPassword.getPassword());
        nuevoUsuario.setPasswordHash(passwordHash);
        nuevoUsuario.setInstructor(checkInstructor.isSelected());

        DataAccess da = new DataAccess();
         int nuevoUsuarioId = da.registerUser(nuevoUsuario);
        nuevoUsuarioId = da.registerUser(nuevoUsuario);
        nuevoUsuario.setId(nuevoUsuarioId);
        lblInfoMessage.setText("User registered successFully with Id " + nuevoUsuarioId);
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void checkInstructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInstructorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInstructorActionPerformed

    private void botonAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccesoActionPerformed
     try {
            // Obtiene el usuario desde el acceso de datos usando el email ingresado
            Usuaris usuari = DataAccess.getUser(txtEmail.getText());
            if (usuari != null && usuari.isInstructor()) {
                // Comprobar contraseña
                char[] passwordToVerify = txtPassword.getPassword();
                String userPasswordHashDataBase = usuari.getPasswordHash();
                var result = BCrypt.verifyer().verify(passwordToVerify, userPasswordHashDataBase);
                if (result.verified) {
                    loggedInUser = usuari;
                    // Si la verificación es correcta
                    JOptionPane.showMessageDialog(this, "Login successful. Welcome " + usuari.getNom()); 
                    mainFra.showListFrame(loggedInUser);
                    dispose(); // Cierra el cuadro de diálogo de acceso
                } else {
                    JOptionPane.showMessageDialog(this, "Error: Invalid password");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: User not found or not an instructor");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Access: " + e.getMessage());
        }
    }//GEN-LAST:event_botonAccesoActionPerformed

    private void jMenufileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenufileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenufileActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jMenuReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReturnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jMenuReturnActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Password;
    private javax.swing.JButton botonAcceso;
    private javax.swing.JCheckBox checkInstructor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuReturn;
    private javax.swing.JMenu jMenufile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInfoMessage;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

}